name: JekyllNB

on:
  push:
    branches: [ master ]
jobs:
  build:
    name: nbconvert
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: nbconvert .ipynb
        uses: runsascoded/nbconvert@v1.2
        with:
          args: -t ${{ secrets.GITHUB_TOKEN}}



