name: JekyllNB

on:
  push:
    branches: [ master ]
jobs:
  build:
    name: nbconvert
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret exists
        if: github.event_name == 'push'
        run: |
          if [ -z "$deploy_key" ]
          then
            echo "You do not have a secret named SSH_DEPLOY_KEY.  This means you did not follow the setup instructions carefully.  Please try setting up your repo again with the right secrets."
            exit 1;
          fi
        env:
           deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Check out repository
        uses: actions/checkout@main
        with:
          persist-credentials: false
      - name: convert notebooks and word docs to posts
        uses: ./_action_files
        with:
          BOOL_SAVE_MARKDOWN: true
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY}}
          
          



