name: JekyllNB

on:
  push:
    branches: [ master ]
jobs:
  build:
    name: nbconvert
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: convert notebooks and word docs to posts
        uses: fastai/fastpages@master
        with:
          BOOL_SAVE_MARKDOWN: true
          SSH_DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN}}



